algo_config:
  horizon: 20
  r_lin:
    - 0.1
  q_lin:
    - 1
    - 1
    - 1
    - 1
  n_samples: 600
  warmstart: False
  tau: 0.95
  run_length: 30

task_config:
  ctrl_freq: 10
  pyb_freq: 1000
  info_in_reset: True
  cost: quadratic
  constraints:
    - constraint_form: default_constraint
      constrained_variable: state
      upper_bounds:
        - 10
        - 10
        - 0.2
        - 100
      lower_bounds:
        - -10
        - -10
        - -0.2
        - -10
    - constraint_form: default_constraint
      constrained_variable: input
  done_on_violation: True
  disturbances:
    observation:
      - disturbance_func: white_noise
        std: 0.1
    dynamics:
      - disturbance_func: white_noise
        std: 0.1
  init_state:
    init_x: 0.1
    init_x_dot: -0.5
    init_theta: -0.19
    init_theta_dot: -0.5
  randomized_init: False
  init_state_randomization_info:
    init_x:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_x_dot:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_theta:
      distrib: uniform
      low: -0.05
      high: 0.05
    init_theta_dot:
      distrib: uniform
      low: -0.05
      high: 0.05
